name: Testing LFS file in Workflows.

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Update git
          run: |
              sudo apt-get install git
              git --version
        - name: Switch to LFS
          uses: actions/checkout@v2
          with:
            lfs: 'true'  
        - name: Read Dump File
          run: |
            cd ${GITHUB_WORKSPACE}/
            head ./dump.sql
